"""Initial migration

Revision ID: 3d7b9017d85e
Revises: 
Create Date: 2023-07-31 12:55:39.794449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7b9017d85e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorited_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_logo', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('job_city', sa.String(), nullable=True),
    sa.Column('job_state', sa.String(), nullable=True),
    sa.Column('job_min_salary', sa.Integer(), nullable=True),
    sa.Column('job_max_salary', sa.Integer(), nullable=True),
    sa.Column('job_employment_type', sa.String(), nullable=True),
    sa.Column('job_apply_link', sa.String(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('job_qualifications', sa.String(), nullable=True),
    sa.Column('job_responsibilities', sa.String(), nullable=True),
    sa.Column('job_benefits', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorited_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorited_jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
